### PR TITLE
Makefile fixes

### PR DESCRIPTION
**Pull request by plusky**

### CODE REVIEW

**Comment by jsmeix** [comment]
@gozora 
it would help me a lot for building ebiso
in a clean way in the openSUSE build service
if this enhancement was included in an ebiso release.

**Comment by gozora** [comment]
Really have no problem with this merge, I'm bit worried about building ebiso on 32-bit architectures.
Not sure whether there aren't some pitfalls.

**Comment by jsmeix** [comment]
At least for now I do not build ebiso on 32-bit architectures.
I have in ebiso.spec

<pre>
# ebiso is only used by rear to make UEFI bootable ISO images
# on SLE12 systems so that no other architecture except x86_64 is needed
# (if also needed for 32-bit it could be "ExclusiveArch: %ix86 x86_64"):
ExclusiveArch:  x86_64
</pre>

But it is nice to have when ebiso can be built
also on non-x6_64 architectures without the need
for changes in its code.

**Comment by gozora** [comment]
@jsmeix currently I can't recall nothing that could avoid creating EFI bootable ISOs on 32-bit architectures, but it was never tested and I wold not like to put people into trouble especially in such stressful situations like bare metal restores. 
Anyhow I'll put 32-bit testing on my todo list ...

**Pull request merged**
